name: Fleet
options:
  bundleIdPrefix: com.fleet
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

packages:
  GoogleSignIn:
    url: https://github.com/google/GoogleSignIn-iOS
    from: "8.0.0"
  FirebaseSDK:
    url: https://github.com/firebase/firebase-ios-sdk
    from: "11.0.0"

targets:
  Fleet:
    type: application
    platform: iOS
    sources:
      - Fleet/Sources
    resources:
      - Fleet/Resources
    dependencies:
      - package: GoogleSignIn
        product: GoogleSignIn
      - package: GoogleSignIn
        product: GoogleSignInSwift
      - package: FirebaseSDK
        product: FirebaseAuth
      - package: FirebaseSDK
        product: FirebaseFirestore
    settings:
      base:
        SWIFT_VERSION: "5.9"
        DEVELOPMENT_TEAM: ""
        PRODUCT_BUNDLE_IDENTIFIER: com.fleet.app
        INFOPLIST_FILE: Fleet/Resources/Info.plist
        GENERATE_INFOPLIST_FILE: false
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
  FleetTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - FleetTests
    dependencies:
      - target: Fleet
    settings:
      base:
        SWIFT_VERSION: "5.9"
        GENERATE_INFOPLIST_FILE: true
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Fleet.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/Fleet"
        BUNDLE_LOADER: "$(TEST_HOST)"
