import XCTest
@testable import Fleet

final class FleetEventTests: XCTestCase {

    // MARK: - Initialization

    func testBasicInitialization() {
        let date = Date(timeIntervalSince1970: 1_700_000_000)
        let event = FleetEvent(title: "Oil Change", vehicleName: "Tesla Model 3", date: date, category: .maintenance, vehicleId: UUID())

        XCTAssertEqual(event.title, "Oil Change")
        XCTAssertEqual(event.vehicleName, "Tesla Model 3")
        XCTAssertEqual(event.date, date)
        XCTAssertEqual(event.category, .maintenance)
    }

    func testAutoGeneratedID() {
        let e1 = FleetEvent(title: "A", vehicleName: "B", date: Date(), category: .registration, vehicleId: UUID())
        let e2 = FleetEvent(title: "A", vehicleName: "B", date: Date(), category: .registration, vehicleId: UUID())
        XCTAssertNotEqual(e1.id, e2.id)
    }

    // MARK: - Categories

    func testRegistrationCategory() {
        let event = FleetEvent(title: "Renewal", vehicleName: "Car", date: Date(), category: .registration, vehicleId: UUID())
        XCTAssertEqual(event.category, .registration)
        XCTAssertEqual(event.category.rawValue, "registration")
    }

    func testInsuranceCategory() {
        let event = FleetEvent(title: "Renewal", vehicleName: "Car", date: Date(), category: .insurance, vehicleId: UUID())
        XCTAssertEqual(event.category, .insurance)
        XCTAssertEqual(event.category.rawValue, "insurance")
    }

    func testMaintenanceCategory() {
        let event = FleetEvent(title: "Oil Change", vehicleName: "Car", date: Date(), category: .maintenance, vehicleId: UUID())
        XCTAssertEqual(event.category, .maintenance)
        XCTAssertEqual(event.category.rawValue, "maintenance")
    }

    func testRecallCategory() {
        let event = FleetEvent(title: "Recall", vehicleName: "Car", date: Date(), category: .recall, vehicleId: UUID())
        XCTAssertEqual(event.category, .recall)
        XCTAssertEqual(event.category.rawValue, "recall")
    }

    // MARK: - Day Computed Property

    func testDayFormatting() {
        var calendar = Calendar(identifier: .gregorian)
        calendar.timeZone = TimeZone.current
        let components = DateComponents(year: 2025, month: 3, day: 5)
        let date = calendar.date(from: components)!
        let event = FleetEvent(title: "Test", vehicleName: "Car", date: date, category: .maintenance, vehicleId: UUID())
        XCTAssertEqual(event.day, "05")
    }

    func testDayFormattingDoubleDigit() {
        var calendar = Calendar(identifier: .gregorian)
        calendar.timeZone = TimeZone.current
        let components = DateComponents(year: 2025, month: 3, day: 25)
        let date = calendar.date(from: components)!
        let event = FleetEvent(title: "Test", vehicleName: "Car", date: date, category: .maintenance, vehicleId: UUID())
        XCTAssertEqual(event.day, "25")
    }

    // MARK: - Month Computed Property

    func testMonthFormatting() {
        var calendar = Calendar(identifier: .gregorian)
        calendar.timeZone = TimeZone.current
        let components = DateComponents(year: 2025, month: 3, day: 15)
        let date = calendar.date(from: components)!
        let event = FleetEvent(title: "Test", vehicleName: "Car", date: date, category: .maintenance, vehicleId: UUID())
        XCTAssertEqual(event.month, "Mar")
    }

    func testMonthFormattingDecember() {
        var calendar = Calendar(identifier: .gregorian)
        calendar.timeZone = TimeZone.current
        let components = DateComponents(year: 2025, month: 12, day: 1)
        let date = calendar.date(from: components)!
        let event = FleetEvent(title: "Test", vehicleName: "Car", date: date, category: .maintenance, vehicleId: UUID())
        XCTAssertEqual(event.month, "Dec")
    }

    func testMonthFormattingJanuary() {
        var calendar = Calendar(identifier: .gregorian)
        calendar.timeZone = TimeZone.current
        let components = DateComponents(year: 2025, month: 1, day: 1)
        let date = calendar.date(from: components)!
        let event = FleetEvent(title: "Test", vehicleName: "Car", date: date, category: .maintenance, vehicleId: UUID())
        XCTAssertEqual(event.month, "Jan")
    }

    // MARK: - Identifiable

    func testIdentifiable() {
        let event = FleetEvent(title: "Test", vehicleName: "Car", date: Date(), category: .maintenance, vehicleId: UUID())
        XCTAssertNotNil(event.id)
    }

    // MARK: - Edge Cases

    func testEmptyTitle() {
        let event = FleetEvent(title: "", vehicleName: "", date: Date(), category: .maintenance, vehicleId: UUID())
        XCTAssertEqual(event.title, "")
        XCTAssertEqual(event.vehicleName, "")
    }

    func testVeryLongTitle() {
        let longTitle = String(repeating: "T", count: 10_000)
        let event = FleetEvent(title: longTitle, vehicleName: "Car", date: Date(), category: .maintenance, vehicleId: UUID())
        XCTAssertEqual(event.title.count, 10_000)
    }

    func testUnicodeInTitle() {
        let event = FleetEvent(title: "\u{1F527} Maintenance", vehicleName: "\u{1F697} My Car", date: Date(), category: .maintenance, vehicleId: UUID())
        XCTAssertTrue(event.title.contains("\u{1F527}"))
        XCTAssertTrue(event.vehicleName.contains("\u{1F697}"))
    }

    func testEpochDate() {
        let event = FleetEvent(title: "Test", vehicleName: "Car", date: Date(timeIntervalSince1970: 0), category: .maintenance, vehicleId: UUID())
        XCTAssertFalse(event.day.isEmpty)
        XCTAssertFalse(event.month.isEmpty)
    }

    func testFarFutureDate() {
        let event = FleetEvent(title: "Test", vehicleName: "Car", date: Date(timeIntervalSince1970: 4_000_000_000), category: .maintenance, vehicleId: UUID())
        XCTAssertFalse(event.day.isEmpty)
        XCTAssertFalse(event.month.isEmpty)
    }
}
